let para = document.createElement('p');
para.innerText = "Hey I'm red";
let body = document.querySelector('body');
body.appendChild(para);
para.classList.add('red');
let head = document.createElement('h3');
head.innerText = "I'm a Blue h3";
body.appendChild(head);
head.classList.add('blue');
let div = document.createElement('div');
// head.innerText = "I'm a Blue h3";
body.appendChild(div);
div.classList.add('blborder');
div.classList.add('pibc');
let divhead = document.createElement('h1');
divhead.innerText = "I'm a Div";
let divpra = document.createElement('p');
divpra.innerText = "ME TOO";
div.appendChild(divhead);
div.appendChild(divpra);