let body = document.querySelector('body');
let btn = document.createElement('button');
btn.innerHTML = "Click me";
let input = document.createElement('input');
body.appendChild(input);
body.appendChild(btn);
btn.setAttribute("placeholder",'username');;
btn.setAttribute("id",'btn');
let button = document.querySelector('button');
button = document.getElementById('btn');
button.classList.add('bcblue');
button.classList.add('white');
let head = document.createElement('h1');
body.appendChild(head);
head.innerText = "DOM Practice";
head.classList.add('purple');
head.classList.add('underline');
let para = document.createElement('p');
body.appendChild(para);
para.innerHTML = "Apna College <b>Delta</b> Practice";